import React, { Fragment } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function Layout(props: { children: React.ReactNode; draft: React.ReactNode }) {
  const { children, draft } = props

  return (
    <Fragment>
      {children}
      {draft}
    </Fragment>
  )
}
